name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  GMAPS_KEY: ${{ secrets.GMAPS_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v3

      # Setup Python 3.9
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      
      # Install mlflow
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # Train Model
      - name: Train Model
        run: |
          python app.py
